### ISSUE TITLE
Tilemap._compareChildOrder の引数 a, b の型

### ISSUE THREAD

**Issue by AsterAtwood** [AsterAtwood/rmmv.d.ts#1]
- Sprite
- PIXI.DisplayObject / PIXI.DisplayObjectContainer

あたり？

元はObject。

**Comment by sabakan03** [comment]
spriteId って書いてあるので Sprite でいいのではないでしょうかっ

**Comment by AsterAtwood** [comment]
あっ見てくださってましたか
さば缶さんも問題疑問等あれば好き勝手にissue追加していってくださいね。

a, b はもともとSpriteに無いメンバ z を持っているので、安易にSpriteにしていいものか
悩んでました。実装みたらここにはSpriteしかこないようなので、Spriteにしておきます。
