### ISSUE TITLE
readonly

### ISSUE THREAD

**Issue by AsterAtwood** [AsterAtwood/rmmv.d.ts#2]
``` typescript
get hoge(): any;
```

みたいな感じで書きたいけど、declare class だと書けないよう。

**Comment by sabakan03** [comment]
僕、
readonly hoge: any;
って書いてました。ワーニングはでてるんだけど、一応意図した風には動いてる……かな？

**Comment by AsterAtwood** [comment]
たし蟹…
ほかのライブラリの型定義ファイルも見てみたんですが、
readonlyの場合コメントで注釈入れるだけで済ませているようです。
なのでこれもそれに合わせたいと思います。
