### ISSUE TITLE
Window_ShopCommand的initialize没被换成constructor

### ISSUE THREAD

**Issue by eslym** [AsterAtwood/rmmv.d.ts#6]
rpg_windows.d.ts 的第612行依然用着initialize而不是construtor

**Comment by Leginion** [comment]
已修复。不过没想到fork的项目需要额外设置才有issue，ORZ
https://github.com/LazyKnightX/rmmv.d.ts/commit/89492b6c0cb7f63fb4e903c405420e9bcb303eed
